### ISSUE TITLE
for .vue

### ISSUE THREAD

**Issue by sosnail** [prettier/stylelint-prettier#16]
TypeError: Cannot read property '0' of null
    at H:\hui\node_modules\stylelint-prettier\stylelint-prettier.js:174:69
    at performRules.push.Promise.all.postcssRoots.map.postcssRoot (H:\hui\node_modules\stylelint\lib\lintSource.js:232:13)
    at Array.map (<anonymous>)
    at rules.forEach.ruleName (H:\hui\node_modules\stylelint\lib\lintSource.js:228:22)
    at Array.forEach (<anonymous>)
    at lintPostcssResult (H:\hui\node_modules\stylelint\lib\lintSource.js:196:9)
    at stylelint._getPostcssResult.then.postcssResult (H:\hui\node_modules\stylelint\lib\lintSource.js:153:18)
    at <anonymous>

**Comment by BPScott** [comment]
Hi @sosnail, can you please provide the steps to reproduce this error so that I can try and help you?

**Comment by jpickwell** [comment]
@sosnail, you should include package versions, your stylelint config, and an example file that can reproduce the error.

FWIW, I'm not experiencing that error.

prettier: 1.16.3
stylelint: 9.10.1
stylelint-config-prettier: 5.0.0
stylelint-prettier: 1.0.6

```javascript
// stylelint.config.js
module.exports = { extends: ['stylelint-prettier/recommended'] }
```

**Comment by BPScott** [comment]
Closing this as it is unactionable
