### ISSUE TITLE
Require ES module

### ISSUE THREAD

**Issue by MaxxM59** [prettier/stylelint-prettier#348]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**

    "prettier": "2.8.7",
    "stylelint": "^15.11.0",
    "stylelint-config-prettier": "^9.0.5",
    "stylelint-config-prettier-scss": "^1.0.0",
    "stylelint-config-sass-guidelines": "^10.0.0",
    "stylelint-config-standard": "^34.0.0",
    "stylelint-config-standard-scss": "^11.1.0",
    "stylelint-order": "^6.0.3",
    "stylelint-prettier": "^5.0.0",
    "stylelint-scss": "^5.3.1",

**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**

```

{
    "overrides": [
        {
            "files": [
                "*.scss",
                "**/*.scss"
            ],
            "extends": [
                "stylelint-config-standard",
                "stylelint-config-standard-scss",
                "stylelint-config-sass-guidelines",
                "stylelint-prettier/recommended"
            ],
            "plugins": [
                "stylelint-scss",
                "stylelint-order",
                "stylelint-prettier",
                "stylelint-config-prettier-scss"
            ],
            "customSyntax": "postcss-scss",
            "rules": {
                "prettier/prettier": [
                    "error",
                    {
                        "useTabs": false,
                        "tabWidth": 2,
                        "semi": true,
                        "singleQuote": true,
                        "quoteProps": "consistent",
                        "trailingComma": "es5",
                        "bracketSpacing": true,
                        "arrowParens": "avoid",
                        "printWidth": 120
                    }
                ]
            }
        }
    ]
}
```

**What source code are you linting?**
scss
**What did you expect to happen?**
Format without error
**What actually happened?**

```console
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint-prettier@5.0.0_prettier@2.8.7_stylelint@15.11.0/node_modules/stylelint-prettier/recommended.js from /home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/loaders.js not supported. Instead change the require of recommended.js in /home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/loaders.js to a dynamic import() which is available in all CommonJS modules.     at f._load (node:electron/js2c/asar_bundle:2:13377)     at module.exports (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/import-fresh@3.3.0/node_modules/import-fresh/index.js:32:59)     at Object.loadJsSync (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/loaders.js:17:12)     at .js (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint@15.11.0_typescript@5.2.2/node_modules/stylelint/lib/createStylelint.js:26:47)     at #loadConfiguration (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/Explorer.js:92:30)     at #readConfiguration (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/Explorer.js:77:80)     at async load (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/Explorer.js:20:48)     at async Explorer.load (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/Explorer.js:23:20)     at async extendConfig (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint@15.11.0_typescript@5.2.2/node_modules/stylelint/lib/augmentConfig.js:184:19)     at async augmentConfigBasic (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint@15.11.0_typescript@5.2.2/node_modules/stylelint/lib/augmentConfig.js:57:20)     at async augmentConfigFull (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint@15.11.0_typescript@5.2.2/node_modules/stylelint/lib/augmentConfig.js:111:24)     at async load (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/Explorer.js:20:20)     at async Explorer.load (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.2.2/node_modules/cosmiconfig/dist/Explorer.js:23:20)     at async getConfigForFile (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint@15.11.0_typescript@5.2.2/node_modules/stylelint/lib/getConfigForFile.js:61:5)     at async isPathIgnored (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint@15.11.0_typescript@5.2.2/node_modules/stylelint/lib/isPathIgnored.js:24:17)     at async lintSource (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint@15.11.0_typescript@5.2.2/node_modules/stylelint/lib/lintSource.js:41:20)     at async Function.standalone [as lint] (/home/me/Documents/Perso/cda-project/node_modules/.pnpm/stylelint@15.11.0_typescript@5.2.2/node_modules/stylelint/lib/standalone.js:125:26)     at async ZR.lintDocument (/home/me/.vscode/extensions/stylelint.vscode-stylelint-1.3.0/dist/start-server.js:71:5691)     at async y2 (/home/me/.vscode/extensions/stylelint.vscode-stylelint-1.3.0/dist/start-server.js:70:30584)     at async LE.CE (/home/me/.vscode/extensions/stylelint.vscode-stylelint-1.3.0/dist/start-server.js:71:70761)     at async Yh.n1 (/home/me/.vscode/extensions/stylelint.vscode-stylelint-1.3.0/dist/start-server.js:71:10026)     at async Yh.o1 (/home/me/.vscode/extensions/stylelint.vscode-stylelint-1.3.0/dist/start-server.js:71:11032)     at async /home/me/.vscode/extensions/stylelint.vscode-stylelint-1.3.0/dist/start-server.js:71:8933
```

I didn't spend much time setting stylelint so I might have missed something. Basically everything was working great except it didn't format well. 

Formatting actually works (except for error notification), but since I'm using other tools it crashes because of the error.

![image](https://github.com/prettier/stylelint-prettier/assets/87809496/8392bab6-12b9-47e4-9624-159c15173b6d)

**Comment by BPScott** [comment]
You appear to be using stlylelint-prettier v5.0.0 with stylelint 15.11.0. 

v5.0.0 only supports stylelint v16 and up, per [the changelog](https://github.com/prettier/stylelint-prettier/blob/main/CHANGELOG.md#500-2023-12-10). You need to use either stlyelint v15 with stylelint-prettier v4, or stylelint v16 with stylelint-prettier v5.
